export const poem = {
  title: "\"Student of Clouds\" by Billy Collins",
  lines: [
    "The emotion is to be found in the clouds,",
    "not in the green solids of the sloping hills",
    "or even in the gray signatures of rivers,",
    "according to Constable, who was a student of clouds",
    "and filled shelves of sketchbooks with their motion,",
    "their lofty gesturing and sudden implication of weather.",

    "Outdoors, he must have looked up thousands of times,",
    "his pencil trying to keep pace with their high voyaging",
    "and the silent commotion of their eddying and flow.",
    "Clouds would move beyond the outlines he would draw",
    "as they moved within themselves, tumbling into their centers",
    "and swirling off at the burning edges in vapors",
    "to dissipate into the universal blue of the sky.",

    "In photographs we can stop all this movement now",
    "long enough to tag them with their Latin names.",
    "Cirrus, nimbus, stratocumulus —",
    "dizzying, romantic, authoritarian —",
    "they bear their titles over the schoolhouses below",
    "where their shapes and meanings are memorized.",

    "High on the soft blue canvases of Constable",
    "they are stuck in pigment but his clouds appear",
    "to be moving still in the wind of his brush,",
    "inching out of England and the nineteenth century",
    "and sailing over these meadows where I am walking,",
    "bareheaded beneath this cupola of motion,",
    "my thoughts arranged like paint on a high blue ceiling."
  ],
  stanzas: [
    "The emotion is to be found in the clouds, not in the green solids of the sloping hills or even in the gray signatures of rivers, according to Constable, who was a student of clouds and filled shelves of sketchbooks with their motion, their lofty gesturing and sudden implication of weather.",

    "Outdoors, he must have looked up thousands of times, his pencil trying to keep pace with their high voyaging and the silent commotion of their eddying and flow. Clouds would move beyond the outlines he would draw as they moved within themselves, tumbling into their centers and swirling off at the burning edges in vapors to dissipate into the universal blue of the sky.",

    "In photographs we can stop all this movement now long enough to tag them with their Latin names. Cirrus, nimbus, stratocumulus — dizzying, romantic, authoritarian — they bear their titles over the schoolhouses below where their shapes and meanings are memorized.",

    "High on the soft blue canvases of Constable they are stuck in pigment but his clouds appear to be moving still in the wind of his brush, inching out of England and the nineteenth century and sailing over these meadows where I am walking, bareheaded beneath this cupola of motion, my thoughts arranged like paint on a high blue ceiling."
  ],

  full: "The emotion is to be found in the clouds, not in the green solids of the sloping hills or even in the gray signatures of rivers, according to Constable, who was a student of clouds and filled shelves of sketchbooks with their motion, their lofty gesturing and sudden implication of weather. Outdoors, he must have looked up thousands of times, his pencil trying to keep pace with their high voyaging and the silent commotion of their eddying and flow. Clouds would move beyond the outlines he would draw as they moved within themselves, tumbling into their centers and swirling off at the burning edges in vapors to dissipate into the universal blue of the sky. In photographs we can stop all this movement now long enough to tag them with their Latin names. Cirrus, nimbus, stratocumulus — dizzying, romantic, authoritarian — they bear their titles over the schoolhouses below where their shapes and meanings are memorized. High on the soft blue canvases of Constable they are stuck in pigment but his clouds appear to be moving still in the wind of his brush, inching out of England and the nineteenth century and sailing over these meadows where I am walking, bareheaded beneath this cupola of motion, my thoughts arranged like paint on a high blue ceiling."
};

export const styledPoem = {
  lines: [
    { text: "The emotion is to be found in the clouds,", class: "lg", stanza: 1 },
    { text: "not in the green solids of the sloping hills", class: "sm", stanza: 1 },
    { text: "or even in the gray signatures of rivers,", class: "sm", stanza: 1 },
    { text: "", class: "br", stanza: 0 },
    { text: "according to Constable,", class: "lg", stanza: 1 },
    { text: "who was a student of clouds", class: "sm", stanza: 1 },
    { text: "and filled shelves of sketchbooks", class: "md", stanza: 1 },
    { text: "with their motion,", class: "sm", stanza: 1 },
    { text: "their lofty gesturing", class: "md", stanza: 1 },
    { text: "and sudden implication of weather.", class: "lg", stanza: 1 },
    { text: "", class: "br", stanza: 0 },
    { text: "Outdoors, he must have looked up thousands of times,", class: "sm", stanza: 2 },
    { text: "his pencil trying to keep pace with their high voyaging", class: "md", stanza: 2 },
    { text: "and the silent commotion of their eddying and flow.", class: "sm", stanza: 2 },
    { text: "", class: "br", stanza: 0 },
    { text: "Clouds would move beyond the outlines he would draw", class: "sm", stanza: 2 },
    { text: "as they moved within themselves,", class: "md", stanza: 2 },
    { text: "tumbling into their centers", class: "lg", stanza: 2 },
    { text: "and swirling off at the burning edges in vapors", class: "lg", stanza: 2 },
    { text: "to dissipate into the universal blue of the sky.", class: "sm", stanza: 2 },
    { text: "", class: "br", stanza: 0 },
    { text: "In photographs we can stop all this movement now", class: "sm", stanza: 3 },
    { text: "long enough to tag them with their Latin names.", class: "md", stanza: 3 },
    { text: "", class: "br", stanza: 0 },
    { text: "Cirrus, nimbus, stratocumulus —", class: "md", stanza: 3 },
    { text: "dizzying, romantic, authoritarian —", class: "lg", stanza: 3 },
    { text: "they bear their titles over the schoolhouses below", class: "sm", stanza: 3 },
    { text: "where their shapes and meanings are memorized.", class: "sm", stanza: 3 },
    { text: "", class: "br", stanza: 0 },
    { text: "High on the soft blue canvases of Constable", class: "sm", stanza: 4 },
    { text: "they are stuck in pigment but his clouds appear", class: "md", stanza: 4 },
    { text: "to be moving still in the wind of his brush,", class: "md", stanza: 4 },
    { text: "", class: "br", stanza: 0 },
    { text: "inching out of England and the nineteenth century", class: "sm", stanza: 4 },
    { text: "and sailing over these meadows where I am walking,", class: "lg", stanza: 4 },
    { text: "bareheaded beneath this cupola of motion,", class: "lg", stanza: 4 },
    { text: "my thoughts arranged like paint on a high blue ceiling.", class: "sm", stanza: 4 }
  ],

  stanzas: [
    { text: "The emotion is to be found in the clouds, not in the green solids of the sloping hills or even in the gray signatures of rivers, according to Constable, who was a student of clouds and filled shelves of sketchbooks with their motion, their lofty gesturing and sudden implication of weather.", class: "" },
    { text: "Outdoors, he must have looked up thousands of times, his pencil trying to keep pace with their high voyaging and the silent commotion of their eddying and flow. Clouds would move beyond the outlines he would draw as they moved within themselves, tumbling into their centers and swirling off at the burning edges in vapors to dissipate into the universal blue of the sky.", class: "" },
    { text: "In photographs we can stop all this movement now long enough to tag them with their Latin names. Cirrus, nimbus, stratocumulus — dizzying, romantic, authoritarian — they bear their titles over the schoolhouses below where their shapes and meanings are memorized.", class: "" },
    { text: "High on the soft blue canvases of Constable they are stuck in pigment but his clouds appear to be moving still in the wind of his brush, inching out of England and the nineteenth century and sailing over these meadows where I am walking, bareheaded beneath this cupola of motion, my thoughts arranged like paint on a high blue ceiling.", class: "" }
  ],

  words: [
    { text: "The", class: "" },
    { text: "emotion", class: "md" },
    { text: "is", class: "" },
    { text: "to", class: "" },
    { text: "be", class: "" },
    { text: "found", class: "" },
    { text: "in", class: "md" },
    { text: "the", class: "md" },
    { text: "clouds,", class: "lg" },
    { text: "not", class: "lg" },
    { text: "in", class: "" },
    { text: "the", class: "" },
    { text: "green", class: "md" },
    { text: "solids", class: "md" },
    { text: "of", class: "" },
    { text: "the", class: "" },
    { text: "sloping", class: "md" },
    { text: "hills", class: "lg" },
    { text: "or", class: "" },
    { text: "even", class: "" },
    { text: "in", class: "" },
    { text: "the", class: "" },
    { text: "gray", class: "md" },
    { text: "signatures", class: "lg" },
    { text: "of", class: "" },
    { text: "rivers,", class: "lg" },
    { text: "according", class: "" },
    { text: "to", class: "" },
    { text: "Constable,", class: "" },
    { text: "who", class: "" },
    { text: "was", class: "" },
    { text: "a", class: "" },
    { text: "student", class: "" },
    { text: "of", class: "" },
    { text: "clouds", class: "" },
    { text: "and", class: "" },
    { text: "filled", class: "" },
    { text: "shelves", class: "" },
    { text: "of", class: "" },
    { text: "sketchbooks", class: "" },
    { text: "with", class: "" },
    { text: "their", class: "" },
    { text: "motion,", class: "" },
    { text: "their", class: "" },
    { text: "lofty", class: "" },
    { text: "gesturing", class: "" },
    { text: "and", class: "" },
    { text: "sudden", class: "" },
    { text: "implication", class: "" },
    { text: "of", class: "" },
    { text: "weather.", class: "" },
    { text: "Outdoors,", class: "" },
    { text: "he", class: "" },
    { text: "must", class: "" },
    { text: "have", class: "" },
    { text: "looked", class: "" },
    { text: "up", class: "" },
    { text: "thousands", class: "" },
    { text: "of", class: "" },
    { text: "times,", class: "" },
    { text: "his", class: "" },
    { text: "pencil", class: "" },
    { text: "trying", class: "" },
    { text: "to", class: "" },
    { text: "keep", class: "" },
    { text: "pace", class: "" },
    { text: "with", class: "" },
    { text: "their", class: "" },
    { text: "high", class: "" },
    { text: "voyaging", class: "" },
    { text: "and", class: "" },
    { text: "the", class: "" },
    { text: "silent", class: "" },
    { text: "commotion", class: "" },
    { text: "of", class: "" },
    { text: "their", class: "" },
    { text: "eddying", class: "" },
    { text: "and", class: "" },
    { text: "flow.", class: "" },
    { text: "Clouds", class: "" },
    { text: "would", class: "" },
    { text: "move", class: "" },
    { text: "beyond", class: "" },
    { text: "the", class: "" },
    { text: "outlines", class: "" },
    { text: "he", class: "" },
    { text: "would", class: "" },
    { text: "draw", class: "" },
    { text: "as", class: "" },
    { text: "they", class: "" },
    { text: "moved", class: "" },
    { text: "within", class: "" },
    { text: "themselves,", class: "" },
    { text: "tumbling", class: "" },
    { text: "into", class: "" },
    { text: "their", class: "" },
    { text: "centers", class: "" },
    { text: "and", class: "" },
    { text: "swirling", class: "" },
    { text: "off", class: "" },
    { text: "at", class: "" },
    { text: "the", class: "" },
    { text: "burning", class: "" },
    { text: "edges", class: "" },
    { text: "in", class: "" },
    { text: "vapors", class: "" },
    { text: "to", class: "" },
    { text: "dissipate", class: "" },
    { text: "into", class: "" },
    { text: "the", class: "" },
    { text: "universal", class: "" },
    { text: "blue", class: "" },
    { text: "of", class: "" },
    { text: "the", class: "" },
    { text: "sky.", class: "" },
    { text: "In", class: "" },
    { text: "photographs", class: "" },
    { text: "we", class: "" },
    { text: "can", class: "" },
    { text: "stop", class: "" },
    { text: "all", class: "" },
    { text: "this", class: "" },
    { text: "movement", class: "" },
    { text: "now", class: "" },
    { text: "long", class: "" },
    { text: "enough", class: "" },
    { text: "to", class: "" },
    { text: "tag", class: "" },
    { text: "them", class: "" },
    { text: "with", class: "" },
    { text: "their", class: "" },
    { text: "Latin", class: "" },
    { text: "names.", class: "" },
    { text: "Cirrus,", class: "" },
    { text: "nimbus,", class: "" },
    { text: "stratocumulus-", class: "" },
    { text: "dizzying,", class: "" },
    { text: "romantic,", class: "" },
    { text: "authoritarian-", class: "" },
    { text: "they", class: "" },
    { text: "bear", class: "" },
    { text: "their", class: "" },
    { text: "titles", class: "" },
    { text: "over", class: "" },
    { text: "the", class: "" },
    { text: "schoolhouses", class: "" },
    { text: "below", class: "" },
    { text: "where", class: "" },
    { text: "their", class: "" },
    { text: "shapes", class: "" },
    { text: "and", class: "" },
    { text: "meanings", class: "" },
    { text: "are", class: "" },
    { text: "memorized.", class: "" },
    { text: "High", class: "" },
    { text: "on", class: "" },
    { text: "the", class: "" },
    { text: "soft", class: "" },
    { text: "blue", class: "" },
    { text: "canvases", class: "" },
    { text: "of", class: "" },
    { text: "Constable", class: "" },
    { text: "they", class: "" },
    { text: "are", class: "" },
    { text: "stuck", class: "" },
    { text: "in", class: "" },
    { text: "pigment", class: "" },
    { text: "but", class: "" },
    { text: "his", class: "" },
    { text: "clouds", class: "" },
    { text: "appear", class: "" },
    { text: "to", class: "" },
    { text: "be", class: "" },
    { text: "moving", class: "" },
    { text: "still", class: "" },
    { text: "in", class: "" },
    { text: "the", class: "" },
    { text: "wind", class: "" },
    { text: "of", class: "" },
    { text: "his", class: "" },
    { text: "brush,", class: "" },
    { text: "inching", class: "" },
    { text: "out", class: "" },
    { text: "of", class: "" },
    { text: "England", class: "" },
    { text: "and", class: "" },
    { text: "the", class: "" },
    { text: "nineteenth", class: "" },
    { text: "century", class: "" },
    { text: "and", class: "" },
    { text: "sailing", class: "" },
    { text: "over", class: "" },
    { text: "these", class: "" },
    { text: "meadows", class: "" },
    { text: "where", class: "" },
    { text: "I", class: "" },
    { text: "am", class: "" },
    { text: "walking,", class: "" },
    { text: "bareheaded", class: "" },
    { text: "beneath", class: "" },
    { text: "this", class: "" },
    { text: "cupola", class: "" },
    { text: "of", class: "" },
    { text: "motion,", class: "" },
    { text: "my", class: "" },
    { text: "thoughts", class: "" },
    { text: "arranged", class: "" },
    { text: "like", class: "" },
    { text: "paint", class: "" },
    { text: "on", class: "" },
    { text: "a", class: "" },
    { text: "high", class: "" },
    { text: "blue", class: "" },
    { text: "ceiling.", class: "" }
  ],

  splitLines: [
    {
      left: [
        { text: "The emotion is to be found", class: "" },
        { text: "not in the green solids", class: "" },
        { text: "or even in the gray signatures", class: "" },
        { text: "according to Constable, who was", class: "" },
        { text: "and filled shelves of sketchbooks", class: "" },
        { text: "their lofy gesturing and sudden", class: "" },
      ],
      right: [
        { text: "in the clouds,", class: "" },
        { text: "of the sloping hills", class: "" },
        { text: "of rivers,", class: "" },
        { text: "a student of clouds", class: "" },
        { text: "with their motion,", class: "" },
        { text: "implication of weather.", class: "" },
      ]
    },
    {
      left: [
        { text: "Outdoors, he must have looked up", class: "" },
        { text: "his pencil trying to keep pace with", class: "" },
        { text: "and the silent commotion of", class: "" },
        { text: "Clouds would move", class: "" },
        { text: "he would draw as they moved", class: "" },
        { text: "tumbling into", class: "" },
        { text: "and swirling off", class: "" },
        { text: "to dissipate into", class: "" }
      ],
      right: [
        { text: "thousands of times,", class: "" },
        { text: "their high voyaging", class: "" },
        { text: "their eddying and flow.", class: "" },
        { text: "beyond the outlines", class: "" },
        { text: "within themselves,", class: "" },
        { text: "their centers", class: "" },
        { text: "at the burning edges in vapors", class: "" },
        { text: "the universal blue of the sky.", class: "" }
      ]
    },
    {
      left: [
        { text: "In photographs we can stop", class: "" },
        { text: "long enough to tag them", class: "" },
        { text: "Cirrus, nimbus, stratocumulus—", class: "" },
        { text: "they bear their titles", class: "" },
        { text: "where their shapes and", class: "" },
      ],
      right: [
        { text: "all this movement now", class: "" },
        { text: "with their Latin names.", class: "" },
        { text: "dizzying, romantic, authoritarian—", class: "" },
        { text: "over the schoolhouses below", class: "" },
        { text: "meanings are memorized.", class: "" },
      ]
    },
    {
      left: [
        { text: "High on the soft blue canvases", class: "" },
        { text: "they are stuck in pigment", class: "" },
        { text: "to be moving still", class: "" },
        { text: "inching out of England", class: "" },
        { text: "and sailing over these meadows", class: "" },
        { text: "bareheaded beneath", class: "" },
        { text: "my thoughts arranged like paint", class: "" },
      ],
      right: [
        { text: "of Constable", class: "" },
        { text: "but his clouds appear", class: "" },
        { text: "in the wind of his brush,", class: "" },
        { text: "and the nineteenth century", class: "" },
        { text: "where I am walking,", class: "" },
        { text: "this cupola of motion,", class: "" },
        { text: "on a high blue ceiling.", class: "" },
      ]
    }
  ],

  full: "The emotion is to be found in the clouds, not in the green solids of the sloping hills or even in the gray signatures of rivers, according to Constable, who was a student of clouds and filled shelves of sketchbooks with their motion, their lofty gesturing and sudden implication of weather. Outdoors, he must have looked up thousands of times, his pencil trying to keep pace with their high voyaging and the silent commotion of their eddying and flow. Clouds would move beyond the outlines he would draw as they moved within themselves, tumbling into their centers and swirling off at the burning edges in vapors to dissipate into the universal blue of the sky. In photographs we can stop all this movement now long enough to tag them with their Latin names. Cirrus, nimbus, stratocumulus — dizzying, romantic, authoritarian — they bear their titles over the schoolhouses below where their shapes and meanings are memorized. High on the soft blue canvases of Constable they are stuck in pigment but his clouds appear to be moving still in the wind of his brush, inching out of England and the nineteenth century and sailing over these meadows where I am walking, bareheaded beneath this cupola of motion, my thoughts arranged like paint on a high blue ceiling."
};